version: '3.8'
services:
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=warehouse
    volumes:
      - db-data:/var/lib/mysql
      - ./database/sql-scripts:/docker-entrypoint-initdb.d
volumes:
  db-data:
